---
sudo: required
services:
- docker
env:
  global:
  - IMAGE_NAME=informaticsmatters/fragalysis
install:
- docker build -t "$IMAGE_NAME" .
script:
- docker run "$IMAGE_NAME" /bin/sh -c "cd /usr/local/fragalysis && nosetests"
