sudo: required
services:
  - docker
env:
  global:
    - IMAGE_NAME=xchem/fragalysis
install:
  - docker build -t "$IMAGE_NAME" .
script:
  - docker run xchem/fragalysis /bin/sh -c "cd /usr/local/fragalysis && nosetests"
after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push "${IMAGE_NAME}";
    fi
before_deploy:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
  - docker tag "$IMAGE_NAME" "${IMAGE_NAME}:${version}"
deploy:
  provider: script
  script: docker tag "$IMAGE_NAME" "${IMAGE_NAME}:${TRAVIS_TAG} && docker push "${IMAGE_NAME}:${version}"
  on:
    branch: master
    tags: true
    repo: xchem/fragalysis