sudo: required
services:
  - docker
install:
  - docker build -t xchem/fragalysis .
script:
  - docker run xchem/fragalysis /bin/sh -c "cd /usr/local/fragalysis && nosetests"
after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push xchem/fragalysis;
    fi
